### PR TITLE
Admin prev care resources

### PR DESCRIPTION
**Pull request by AlinaTrukhina**
Add specific resource page, no styling
Add specificResource saga/reducer/router
Add GET and PUT routes to get and edit resources

### CODE REVIEW

**Review by tormodsletteboe — CHANGES_REQUESTED** [review]
@AlinaTrukhina , we have decided to go down a different route. talk to tia, im not merging this pull request. edan showed us how we can have 1 route get all the data. also the specificResourcesSaga.js has some merge lines >>>>>>>>>> HEAD
image

**Comment by tormodsletteboe** [comment]
@AlinaTrukhina , so I guess you talked to Tia, if you fix the issue shown in picture and re push, ill take a look again

**Comment by AlinaTrukhina** [comment]
Ok, I added the fix and re pushed

**Review by tormodsletteboe — COMMENTED** [review]
@AlinaTrukhina looks good

**Pull request merged**
